apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: hello-world
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: hello-world
spec:
  type: LoadBalancer
  loadBalancerIP: 10.235.200.10
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello-world
